### ISSUE TITLE
Host url

### ISSUE THREAD

**Issue by gHashTag** [salute-developers/jazz-web-sdk-demo#4]
How to get Host url to create new client? Now there is an error.
<img width="611" alt="Screenshot 2567-09-14 at 16 01 12" src="https://github.com/user-attachments/assets/610444b0-890e-4bd8-a62d-0b267f993059">

**Comment by chartyom** [comment]
Hi, Dmitrii! 
The localhost domain is now blocked by CORS. To test the demo application, you need to disable web security in the browser. See https://www.google.com/search?q=disable+web+security+chrome 

Use https://salutejazz.ru when creating a client.

**Comment by Kerbalximus** [comment]
Hi!

<img width="1456" alt="Screenshot 2024-12-28 at 22 17 35" src="https://github.com/user-attachments/assets/49d6d6df-58de-4c8b-9557-1329adcea3f2" />


I got the same problem with login by SDK Secret. I tried to disable CORS, but it didn't fix my issue. 
I created workspace in Dev Portal (https://developers.sber.ru/studio/) and released key for SaluteJazz SDK. 

it looks like the official sdk started to receive the usual custom salutejazz home page in response from the api instead of the real response.


Traceback from console:
```
TypeError: Cannot read properties of undefined (reading 'token')
    at index.esm.js:1:1
    at switchMap.js:14:1
    at OperatorSubscriber._this._next (OperatorSubscriber.js:11:1)
    at Subscriber.next (Subscriber.js:34:1)
    at Subscriber._next (Subscriber.js:63:1)
    at Subscriber.next (Subscriber.js:34:1)
    at switchMap.js:14:1
    at OperatorSubscriber._this._next (OperatorSubscriber.js:11:1)
    at Subscriber.next (Subscriber.js:34:1)
    at Observable._subscribe (from.js:55:1)
    at Observable._trySubscribe (Observable.js:38:1)
    at Observable.js:32:1
    at errorContext (errorContext.js:19:1)
    at Observable.subscribe (Observable.js:23:1)
    at switchMap.js:14:1
    at OperatorSubscriber._this._next (OperatorSubscriber.js:11:1)
    at Subscriber.next (Subscriber.js:34:1)
    at tap.js:18:1
    at OperatorSubscriber._this._next (OperatorSubscriber.js:11:1)
    at Subscriber.next (Subscriber.js:34:1)
    at Subscriber._next (Subscriber.js:63:1)
    at Subscriber.next (Subscriber.js:34:1)
    at map.js:7:1
    at OperatorSubscriber._this._next (OperatorSubscriber.js:11:1)
    at Subscriber.next (Subscriber.js:34:1)
    at switchMap.js:14:1
    at OperatorSubscriber._this._next (OperatorSubscriber.js:11:1)
    at Subscriber.next (Subscriber.js:34:1)
    at tap.js:18:1
    at OperatorSubscriber._this._next (OperatorSubscriber.js:11:1)
    at Subscriber.next (Subscriber.js:34:1)
    at Subscriber._next (Subscriber.js:63:1)
    at Subscriber.next (Subscriber.js:34:1)
    at switchMap.js:14:1
    at OperatorSubscriber._this._next (OperatorSubscriber.js:11:1)
    at Subscriber.next (Subscriber.js:34:1)
    at switchMap.js:14:1
    at OperatorSubscriber._this._next (OperatorSubscriber.js:11:1)
    at Subscriber.next (Subscriber.js:34:1)
    at Observable._subscribe (from.js:55:1)
    at Observable._trySubscribe (Observable.js:38:1)
    at Observable.js:32:1
    at errorContext (errorContext.js:19:1)
    at Observable.subscribe (Observable.js:23:1)
    at switchMap.js:14:1
    at OperatorSubscriber._this._next (OperatorSubscriber.js:11:1)
    at Subscriber.next (Subscriber.js:34:1)
    at Observable._subscribe (from.js:55:1)
    at Observable._trySubscribe (Observable.js:38:1)
    at Observable.js:32:1
    at errorContext (errorContext.js:19:1)
    at Observable.subscribe (Observable.js:23:1)
    at switchMap.js:10:1
    at OperatorSubscriber.<anonymous> (lift.js:10:1)
    at Observable.js:27:1
    at errorContext (errorContext.js:19:1)
    at Observable.subscribe (Observable.js:23:1)
    at switchMap.js:14:1
    at OperatorSubscriber._this._next (OperatorSubscriber.js:11:1)
    at Subscriber.next (Subscriber.js:34:1)
    at index.esm.js:1:1
```

i am very impressed with salutejazz and i want to use the sdk in my AI project so please let me know if this problem gets fixed <3

**Comment by chartyom** [comment]
Hi @Kerbalximus 

Use https://salutejazz.ru/ when creating a client.
<img width="932" alt="image" src="https://github.com/user-attachments/assets/fbfb6573-8f27-430a-846f-991ef365b226" />
